export const STICKER_ACTIONS = {
    UPDATE_STICKERS: 'ADD_STICKERS',
    UPDATE_COUNT: 'UPDATE_COUNT'
};

export const FRIEND_ACTIONS = {
    UPDATE_FRIENDS: 'UPDATE_FRIENDS'
};

export const FRIEND_REQUEST_ACTIONS = {
    UPDATE_FRIEND_REQUESTS: 'UPDATE_FRIEND_REQUESTS'
};

export const AUTH_ACTIONS = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
};