export const STICKER_ACTIONS = {
    UPDATE_STICKERS: 'ADD_STICKERS',
    UPDATE_COUNT: 'UPDATE_COUNT'
};

export const FRIEND_ACTIONS = {
    UPDATE_FRIENDS: 'UPDATE_FRIENDS'
};

export const ROUTE_ACTIONS = {
    VIEW_FRIENDS: 'VIEW_FRIENDS',
    VIEW_HOME: 'VIEW_HOME'
};

export const AUTH_ACTIONS = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE'
};